### ISSUE TITLE
SimpleMVVM and WiX CustomAction

### ISSUE THREAD

**Issue by brianke** [SimpleMvvm/SimpleMvvmToolkit.Express#4]
I am working on a WiX installer project that requires a CustomAction. The project needs to be built using .Net 4.6.2 to support some required features.

I can create and build the CustomAction until I add a NuGet reference to SimpleMVVM.Express 2.0.0-beta . After adding the reference and trying to rebuild I get the following error message:

> EXEC : error : System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Fies (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Net.WebSockets.Client.dll'.
>  at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>  at System.IO.File.GetAttributes(String path)
>  at Microsoft.Deployment.Compression.ArchiveFileStreamContext.OpenFileReadStream(String path, FileAttributes& attributes, DateTime& lastWriteTime)
> 1> at Microsoft.Deployment.Compression.Cab.CabPacker.Pack(IPackStreamContext streamContext, IEnumerable1 files, Int64 maxArchiveSize) 1> at Microsoft.Deployment.Compression.Cab.CabEngine.Pack(IPackStreamContext streamContext, IEnumerable1 files, Int64 maxArchiveSize)
>  at Microsoft.Deployment.Compression.CompressionEngine.Pack(IPackStreamContext streamContext, IEnumerable1 files) 1> at Microsoft.Deployment.Compression.ArchiveInfo.PackFileSet(String sourceDirectory, IDictionary2 fileNames, CompressionLevel compLevel, EventHandler1 progressHandler)  at Microsoft.Deployment.Tools.MakeSfxCA.MakeSfxCA.PackInputFiles(String outputFile, IDictionary2 fileMap)
>  at Microsoft.Deployment.Tools.MakeSfxCA.MakeSfxCA.Build(String output, String sfxdll, IList`1 inputs, TextWriter log)
>  at Microsoft.Deployment.Tools.MakeSfxCA.MakeSfxCA.Main(String[] args

I can submit a project if you need but if you have WiX, simply create a CustomAction project and then add SimpleMVVM.Express to the CustomAction project and build. This should recreate the issue.

**Comment by brianke** [comment]
Please ignore this issue.  I found a solution to a similar issue fixed this issue.  By deleting the folder 

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net471\lib\

 and rebuilding the solution resolved my issue.
